backend:
  name: github
  repo: seungdance/Monique-Smith-McDowell
  branch: main
  base_url: https://moniquewebsite.netlify.app
  auth_endpoint: auth

local_backend: true

media_folder: "website photos"
public_folder: "/website photos"

collections:
  - name: "news"
    label: "News"
    folder: "_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "Short preview text for the news item" }
      - { label: "Content", name: "body", widget: "markdown", hint: "Full content of the news item" }
      - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Optional featured image for the news item" }
      - { label: "Published", name: "published", widget: "boolean", default: true, hint: "Set to false to hide this news item" }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          default: 0,
          hint: "Order for displaying news items (lower numbers appear first)",
        }
